### ISSUE TITLE
FSI example

### ISSUE THREAD

**Issue by jorgensd** [marchirschvogel/ambit#8]
Hi Marc!
I had a look at your FSI demo online, and it seems to be missing several figures and tables. (Link: https://ambit.readthedocs.io/en/latest/documentation.html#fig:channel_flag_setup)

Another question I had is:
- Did you ever verify the Drag, lift and maximum displacement over time?

**Comment by marchirschvogel** [comment]
Hi Jørgen,

Thanks for pointing this out. Indeed, tables and other references get screwed when I convert my .tex file to an .rst file using pandoc, and I will look into it asap to get these fixed.

Since the setup is actually a modification of the original Turek benchmark (geometry- and BC-wise), I have not did the verification against the original results. But, I did verify the solution with the exact same setup from another solver (which was verified for many different setups), and the velocity and displacement fields are identical to machine precision.
But I agree that a 1:1 verification to the original Turek benchmark would be beneficial, and I fill follow up on this soon!

Best,
Marc

**Comment by marchirschvogel** [comment]
The demo is now updated and comparisons to the Turek reference solutions are carried out: https://ambit.readthedocs.io/en/latest/documentation.html#demo-fsi
